import os
import re
import time
import shutil
from queue import Empty
from WingLoop_Library import Aswing_Director


import subprocess
import glob




__all__ = [
    "VideoPlot_Generate_postscript_file",
    "Generate_Analysis_Videos",
    "Generate_Strobe_Plot",
]



def VideoPlot_Generate_postscript_file(
    geometry_filename,
    reference_folder,
    input_files,
    video_folder,
    aswing_alias="aswing_stable",
    movie_time_limit=60.0,
    movie_start_point=1,
    Dt=0.1,
    movie_chunk_duration=10.0,
    movie_speed_factor=None,
    plot_options=None,
    stable_duration=1.0,
    poll_interval=0.1,
    timeout=30
):
    """
    Launches ASWING, loads a geometry and its associated files, enters OPER mode,
    lets the user issue commands interactively, then captures the resulting plot.ps
    and moves it to the video folder.

    Parameters
    ----------
    geometry_filename : str        - e.g. "aircraft_L20_K0.01_FWT0.4.asw"
    reference_folder  : str        - folder containing the geometry and input files
    input_files       : list[str]  - ordered list of files to load (point, settings, results…)
    video_folder      : str        - destination folder for the output .ps file
    aswing_alias      : str        - shell alias or path for the ASWING executable
    movie_time_limit  : float      - ASWING movie time limit, normally T_sim
    movie_start_point : int        - first ASWING time-march point used for the movie
    Dt                : float      - simulation time step, used to advance chunk start points
    movie_chunk_duration : float   - kept for backward compatibility; not used by default
    movie_speed_factor : float     - ASWING slow-motion factor. Bigger means faster.
    plot_options : dict            - optional ASWING plot toggles, e.g. camera_movement, wake_plotting
    stable_duration   : float      - seconds plot.ps must be unchanged to be considered done
    poll_interval     : float      - seconds between stability checks
    timeout           : float      - max seconds to wait for plot.ps before raising TimeoutError

    Returns
    -------
    target_ps : str - absolute path of the moved .ps file
    """
    base_dir = os.getcwd()

    # ── Output folder (created before ASWING shifts CWD) ──────────────────
    target_dir = os.path.join(base_dir, video_folder)
    os.makedirs(target_dir, exist_ok=True)
    print(f"[ASW_Helpers] Output folder ready: {target_dir}")

    # ── Launch ASWING ──────────────────────────────────────────────────────
    print(f"[ASW_Helpers] Starting ASWING with geometry: {geometry_filename}")
    ASW_handler = Aswing_Director(
        aswing_path=None,
        aswing_alias=aswing_alias,
        wait_time=0.03,
        finished_writing_file_check_timestep=0.001
    )
    ASW_handler.start_aswing(
        directory=reference_folder,
        filename=geometry_filename,
        print_output=True
    )

    # ── Load all provided input files ──────────────────────────────────────
    print(f"[ASW_Helpers] Loading {len(input_files)} input file(s)...")
    for f in input_files:
        print(f"[ASW_Helpers]   → {f}")
        ASW_handler.Load_Files_ASW(f)

    # ── Enter OPER and interactive loop ────────────────────────────────────
    print(f"[ASW_Helpers] Entering OPER mode...")
    ASW_handler.send_command_and_receive("OPER")

    print()
    print("=" * 60)
    print("[ASW_Helpers] INTERACTIVE MODE")
    print("  You can now modify how the video is generated by ASWING.")
    print("  Send any ASWING command to adjust plot settings, views,")
    print("  or animation parameters before the hardcopy is triggered.")
    print("  When you are satisfied with the configuration, type Y to")
    print("  proceed with the hardcopy and generate the postscript file.")
    print("=" * 60)
    print()

    while True:
        ii = input("  [ASW_Helpers] (Y to proceed with hardcopy): ")
        if ii.strip().upper() == "Y":
            break
        ASW_handler.send_command_and_receive(ii)

    print()

    # ── Trigger hardcopy ───────────────────────────────────────────────────
    print("[ASW_Helpers] Triggering hardcopy sequence...")
    option_menu_output, _ = ASW_handler.send_command_and_receive("O")      # Entra nel sottomenu Option
    _apply_aswing_plot_options(ASW_handler, option_menu_output, plot_options)
    ASW_handler.send_command_and_receive("H")      # Attiva la registrazione video (Hardcopy)
    ASW_handler.send_command_and_receive("T")      # Seleziona 'Time-of-movie limit'
    ASW_handler.send_command_and_receive(str(float(movie_time_limit)))  # Imposta il limite reale della simulazione

    if movie_speed_factor is None:
        # ASWING can stop at an interactive "Continue with new slo-mo factor?"
        # prompt for movies longer than roughly ten seconds. A larger slow-mo
        # factor makes the true ASWING movie render faster without changing the
        # simulated trajectory stored in the PostScript frames.
        movie_speed_factor = max(1.0, float(movie_time_limit) / 5.0)

    print(f"[ASW_Helpers] Setting ASWING movie speed factor: {movie_speed_factor:.3f}")
    ASW_handler.send_command_and_receive("S")
    ASW_handler.send_command_and_receive(str(float(movie_speed_factor)))
    ASW_handler.send_command_and_receive(" ")      # Premi Invio per uscire da Option

    print(f"[ASW_Helpers] Selecting movie start point: {movie_start_point}")
    ASW_handler.send_command_and_receive(str(int(movie_start_point)))

    ASW_handler.send_command_and_receive(".")      # Passa alla modalità transitoria
    print("[ASW_Helpers] Starting ASWING View movie command...")
    stdout, _ = ASW_handler.send_command_and_receive("V", custom_timer=1.0)  # Avvia il rendering (View movie)
    _answer_movie_speed_prompt_if_present(
        ASW_handler,
        initial_stdout=stdout,
        movie_speed_factor=movie_speed_factor,
        timeout=3.0,
    )

    # ── Wait for plot.ps ───────────────────────────────────────────────────
    source_ps = os.path.join(base_dir, reference_folder, "plot.ps")
    target_ps = os.path.join(target_dir, "plot_" + geometry_filename.replace(".asw", ".ps"))

    print(f"[ASW_Helpers] Waiting for plot.ps to finish writing: {source_ps}")
    _wait_for_file_stable(source_ps, stable_duration, poll_interval, timeout)
    print(f"[ASW_Helpers] plot.ps is stable.")

    # ── Append extra hardcopies (workaround for glitchy last pages) ────────
    N = 3
    print(f"[ASW_Helpers] Appending {N} extra hardcopy page(s) to flush ASWING buffer...")
    for i in range(N):
        ASW_handler.send_command_and_receive("H")
    time.sleep(0.5)

    # ── Strip the glitchy trailing pages ──────────────────────────────────
    print(f"[ASW_Helpers] Removing last {N} glitchy page(s) from plot.ps...")
    _delete_last_n_pages_ps(source_ps, N)

    # ── Move to destination ────────────────────────────────────────────────
    print(f"[ASW_Helpers] Moving postscript file to video folder...")
    print(f"[ASW_Helpers]   {source_ps}")
    print(f"[ASW_Helpers]   → {target_ps}")
    shutil.move(source_ps, target_ps)
    print(f"[ASW_Helpers] Done. Postscript file ready at: {target_ps}")

    return target_ps


def _answer_movie_speed_prompt_if_present(
    ASW_handler,
    initial_stdout="",
    movie_speed_factor=1.0,
    timeout=3.0,
):
    """
    ASWING asks an extra slow-motion prompt for longer movies. If we do not
    answer it, the Python side waits forever for plot.ps even though ASWING is
    waiting for keyboard input.
    """
    buffer = initial_stdout or ""
    start_time = time.time()

    while time.time() - start_time < timeout:
        if "Enter slow-motion factor" in buffer:
            print("[ASW_Helpers] ASWING requested a movie speed factor.")
            ASW_handler.send_command_and_receive(str(float(movie_speed_factor)), custom_timer=0.3)
            return True

        if "Continue with new slo-mo factor" in buffer:
            print("[ASW_Helpers] ASWING requested a movie speed confirmation.")
            ASW_handler.send_command_and_receive("Y", custom_timer=0.3)
            ASW_handler.send_command_and_receive(str(float(movie_speed_factor)), custom_timer=0.3)
            return True

        try:
            line = ASW_handler.stdout_queue.get_nowait()
            buffer += line
            if ASW_handler.print_output:
                print(line, end="")
        except Empty:
            time.sleep(0.05)

    return False


def _apply_aswing_plot_options(ASW_handler, option_menu_output, plot_options):
    if not plot_options:
        return

    option_specs = {
        "camera_movement": {
            "command": "M",
            "label": "camera-movement",
            "default": True,
        },
        "wake_plotting": {
            "command": "W",
            "label": "wake-plotting",
            "default": False,
        },
    }

    menu_text = option_menu_output or ""
    for option_name, desired_value in plot_options.items():
        if option_name not in option_specs:
            continue

        spec = option_specs[option_name]
        desired_state = bool(desired_value)
        current_state = _parse_aswing_toggle_state(
            menu_text,
            spec["label"],
            spec["default"],
        )

        print(
            f"[ASW_Helpers] Plot option {option_name}: "
            f"current={current_state}, desired={desired_state}"
        )

        if current_state != desired_state:
            menu_text, _ = ASW_handler.send_command_and_receive(spec["command"])
            print(f"[ASW_Helpers] Plot option {option_name} toggled.")


def _parse_aswing_toggle_state(menu_text, label, default_value):
    pattern = rf"\b{re.escape(label)}\s+toggle\s+([TF])\b"
    match = re.search(pattern, menu_text or "", flags=re.IGNORECASE)
    if not match:
        print(
            f"[ASW_Helpers] Warning: could not read ASWING option '{label}'. "
            f"Assuming default={default_value}."
        )
        return bool(default_value)

    return match.group(1).upper() == "T"


def _delete_last_n_pages_ps(filepath, n):
    """Remove the last n pages from a PostScript file in-place."""
    with open(filepath, "r", encoding="latin-1") as f:
        content = f.read()

    page_positions = [m.start() for m in re.finditer(r"^%%Page:", content, re.MULTILINE)]

    if n >= len(page_positions):
        print(f"[ASW_Helpers] Warning: file has {len(page_positions)} page(s), "
              f"cannot remove {n} — skipping.")
        return

    cut_position = page_positions[-n]
    truncated = content[:cut_position].rstrip() + "\n%%Trailer\n%%EOF\n"

    with open(filepath, "w", encoding="latin-1") as f:
        f.write(truncated)

    print(f"[ASW_Helpers] Page trim complete: "
          f"{len(page_positions)} → {len(page_positions) - n} pages.")


def _wait_for_file_stable(filepath, stable_duration, poll_interval, timeout):
    """Private helper — polls until filepath is unchanged for stable_duration seconds."""
    deadline = time.time() + timeout
    last_size, last_mtime = -1, -1
    stable_since = None

    while time.time() < deadline:
        if os.path.exists(filepath):
            try:
                stat = os.stat(filepath)
                size, mtime = stat.st_size, stat.st_mtime
            except OSError:
                time.sleep(poll_interval)
                continue

            if size == last_size and mtime == last_mtime:
                if stable_since is None:
                    stable_since = time.time()
                elif time.time() - stable_since >= stable_duration:
                    return
            else:
                last_size, last_mtime = size, mtime
                stable_since = None
        else:
            last_size, last_mtime = -1, -1
            stable_since = None

        time.sleep(poll_interval)

    raise TimeoutError(f"[ASW_Helpers] Timed out waiting for '{filepath}' "
                       f"to stabilise after {timeout}s")












import os
import shutil
import subprocess
import glob

def Generate_Analysis_Videos(
    ps_filepath, 
    Dt=0.02, 
    videofile ="gif",
    transpose=None, 
    quality="medium", 
    keep_frames=False,
    max_frames=600,
    target_duration=None
):
    """
    Converts a multi-page PostScript file into MP4, GIF, and WebM.
    
    Parameters
    ----------
    ps_filepath : str   - Full path to the .ps file
    Dt          : float - Seconds per frame (e.g., 0.02)
    transpose   : int   - None, 1 (90 CW), 2 (90 CCW)
    quality     : str   - "high", "medium", "low" (controls DPI and compression)
    keep_frames : bool  - If True, PNG frames are not deleted
    max_frames  : int   - Maximum frames sent to Ghostscript/FFmpeg.
                          Longer simulations are automatically downsampled,
                          while preserving the video duration.
    target_duration : float
                          If set, the exported movie is played in at most this
                          many seconds. Useful for GIF previews of long runs.
    """

    if isinstance(ps_filepath, (list, tuple)):
        if videofile != "mp4":
            raise ValueError("Chunked video generation currently supports mp4 output only.")

        segment_paths = []
        for i, ps_chunk in enumerate(ps_filepath, start=1):
            print(f"[Video] Converting chunk {i}/{len(ps_filepath)} to MP4...")
            segment_paths.append(
                Generate_Analysis_Videos(
                    ps_chunk,
                    Dt=Dt,
                    videofile="mp4",
                    transpose=transpose,
                    quality=quality,
                    keep_frames=keep_frames,
                    max_frames=max_frames,
                    target_duration=target_duration,
                )
            )

        return _concat_mp4_segments(segment_paths)
    
    # 1. Setup paths and dependencies
    _check_dependency("gs", "Ghostscript -> sudo apt install ghostscript")
    _check_dependency("ffmpeg", "FFmpeg -> sudo apt install ffmpeg")

    ps_filepath, frame_stride, n_pages_before, n_pages_after = _downsample_ps_for_video(
        ps_filepath,
        max_frames=max_frames,
    )

    base_path = os.path.splitext(ps_filepath)[0]
    output_dir = os.path.dirname(ps_filepath)
    frames_dir = base_path + "_frames"
    if target_duration is not None and target_duration > 0 and n_pages_after > 0:
        original_duration = max(float(Dt) * max(n_pages_before - 1, 1), float(Dt))
        export_duration = min(float(target_duration), original_duration)
        fps = max(1.0, n_pages_after / export_duration)
    else:
        effective_dt = Dt * frame_stride
        fps = 1.0 / effective_dt
    
    # Quality Presets
    presets = {
        "high":   {"dpi": 150, "crf_mp4": 18, "crf_webm": 20, "width": 1400},
        "medium": {"dpi": 150, "crf_mp4": 23, "crf_webm": 30, "width": 1000},
        "low":    {"dpi": 72,  "crf_mp4": 28, "crf_webm": 40, "width": 600}
    }
    cfg = presets.get(quality, presets["medium"])

    os.makedirs(frames_dir, exist_ok=True)
    frame_pattern = os.path.join(frames_dir, "frame_%04d.png")

    # 2. Step 1: Rasterize PS to PNG (Ghostscript)
    print(
        f"--- Rasterizing PS at {cfg['dpi']} DPI "
        f"({n_pages_after}/{n_pages_before} frame pages, stride={frame_stride}, fps={fps:.3f}) ---"
    )
    gs_cmd = [
        "gs", "-dBATCH", "-dNOPAUSE", "-dQUIET", "-sDEVICE=png16m",
        f"-r{cfg['dpi']}", f"-sOutputFile={frame_pattern}", ps_filepath
    ]
    _run(gs_cmd, "Ghostscript failed")

    # Verify frames exist
    frames = sorted(glob.glob(os.path.join(frames_dir, "frame_*.png")))
    if not frames:
        raise RuntimeError("No frames generated. Check your .ps file.")

    # Prepare FFmpeg filters (Rotation + Padding/Scaling)
    vf_base = ""
    if transpose:
        vf_base += f"transpose={transpose},"

    # 3. Step 2: Generate MP4
    if videofile == "mp4":
        output_mp4 = base_path + ".mp4"
        print(f"--- Generating MP4 ({quality}) ---")
        mp4_vf = vf_base + "pad=ceil(iw/2)*2:ceil(ih/2)*2" # Ensure even dimensions
        mp4_cmd = [
            "ffmpeg", "-y", "-framerate", str(fps), "-i", frame_pattern,
            "-vf", mp4_vf, "-c:v", "libx264", "-crf", str(cfg['crf_mp4']),
            "-pix_fmt", "yuv420p", output_mp4
        ]
        _run(mp4_cmd, "FFmpeg MP4 failed")

    elif videofile == "gif":
        # 4. Step 3: Generate GIF (High Quality Palette)
        output_gif = base_path + ".gif"
        print(f"--- Generating GIF ({quality}) ---")
        gif_vf = (
            vf_base + 
            f"scale={cfg['width']}:-1:flags=lanczos,split[s0][s1];"
            "[s0]palettegen=stats_mode=full[p];[s1][p]paletteuse=dither=sierra2_4a"
        )
        gif_cmd = [
            "ffmpeg", "-y", "-framerate", str(fps), "-i", frame_pattern,
            "-vf", gif_vf, output_gif
        ]
        _run(gif_cmd, "FFmpeg GIF failed")

    elif videofile == "webp":
        # 5. Step 4: Generate WebM
        output_webm = base_path + ".webm"
        print(f"--- Generating WebM ({quality}) ---")
        webm_cmd = [
            "ffmpeg", "-y", "-framerate", str(fps), "-i", frame_pattern,
            "-vf", vf_base.rstrip(','), # Remove trailing comma if no other filters
            "-c:v", "libvpx-vp9", "-crf", str(cfg['crf_webm']), "-b:v", "0",
            output_webm
        ]
        _run(webm_cmd, "FFmpeg WebM failed")

    # 6. Cleanup
    if not keep_frames:
        print("--- Cleaning up temporary frames ---")
        shutil.rmtree(frames_dir)
    
    print(f"Done. Files created in: {output_dir}")
    if videofile == "mp4":
        return output_mp4
    elif videofile == "gif":
        return output_gif
    elif videofile == "webp":
        return output_webm

def _check_dependency(cmd, install_hint):
    if shutil.which(cmd) is None:
        raise EnvironmentError(f"'{cmd}' not found. {install_hint}")

def _run(cmd, error_prefix):
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(f"{error_prefix}:\n{result.stderr.strip()}")


def _concat_mp4_segments(segment_paths):
    if not segment_paths:
        raise RuntimeError("No MP4 segments were produced.")

    if len(segment_paths) == 1:
        return segment_paths[0]

    output_dir = os.path.dirname(segment_paths[0])
    first_base = os.path.splitext(os.path.basename(segment_paths[0]))[0]
    first_base = re.sub(r"_part\d{3}.*$", "", first_base)
    output_path = os.path.join(output_dir, first_base + "_full.mp4")
    concat_file = os.path.join(output_dir, first_base + "_concat_list.txt")

    with open(concat_file, "w", encoding="utf-8") as f:
        for segment in segment_paths:
            safe_segment = os.path.abspath(segment).replace("'", "'\\''")
            f.write(f"file '{safe_segment}'\n")

    print(f"[Video] Concatenating {len(segment_paths)} MP4 segment(s)...")
    concat_cmd = [
        "ffmpeg", "-y", "-f", "concat", "-safe", "0",
        "-i", concat_file, "-c", "copy", output_path,
    ]
    _run(concat_cmd, "FFmpeg MP4 concat failed")

    try:
        os.remove(concat_file)
    except OSError:
        pass

    print(f"[Video] Concatenated MP4 saved: {output_path}")
    return output_path


def _downsample_ps_for_video(ps_filepath, max_frames=600):
    """Keep at most max_frames PostScript pages before rasterizing a long movie."""
    if max_frames is None or max_frames <= 0:
        return ps_filepath, 1, _count_ps_pages(ps_filepath), _count_ps_pages(ps_filepath)

    with open(ps_filepath, "r", encoding="latin-1") as f:
        content = f.read()

    page_matches = list(re.finditer(r"^%%Page:", content, re.MULTILINE))
    n_pages = len(page_matches)

    if n_pages == 0 or n_pages <= max_frames:
        return ps_filepath, 1, n_pages, n_pages

    stride = max(1, int((n_pages + max_frames - 1) // max_frames))
    keep_indices = list(range(0, n_pages, stride))
    if keep_indices[-1] != n_pages - 1:
        keep_indices.append(n_pages - 1)

    first_page_start = page_matches[0].start()
    header = content[:first_page_start]
    header = re.sub(r"^%%Pages:\s+\d+", f"%%Pages: {len(keep_indices)}", header, count=1, flags=re.MULTILINE)

    page_chunks = []
    for idx in keep_indices:
        start = page_matches[idx].start()
        if idx + 1 < n_pages:
            end = page_matches[idx + 1].start()
        else:
            end = len(content)
        page_chunks.append(content[start:end].rstrip())

    downsampled_path = os.path.splitext(ps_filepath)[0] + f"_downsampled_x{stride}.ps"
    with open(downsampled_path, "w", encoding="latin-1") as f:
        f.write(header.rstrip())
        f.write("\n")
        f.write("\n".join(page_chunks))
        if "%%EOF" not in page_chunks[-1]:
            f.write("\n%%Trailer\n%%EOF\n")

    print(
        f"[Video] Downsampled PostScript pages: {n_pages} -> {len(keep_indices)} "
        f"(stride={stride}, max_frames={max_frames})."
    )

    return downsampled_path, stride, n_pages, len(keep_indices)


def _count_ps_pages(ps_filepath):
    try:
        with open(ps_filepath, "r", encoding="latin-1") as f:
            return sum(1 for line in f if line.startswith("%%Page:"))
    except OSError:
        return 0
    



def Generate_Strobe_Plot(
    ps_filepath, 
    indices, 
    transpose=None, 
    dpi=300, # Defaulted to our new ultra preset
    output_suffix="_strobe",
    mask_region=[50, 2220, 1016, 2570] 
):
    _check_dependency("gs", "Ghostscript -> sudo apt install ghostscript")
    _check_dependency("ffmpeg", "FFmpeg -> sudo apt install ffmpeg")

    base_path = os.path.splitext(ps_filepath)[0]
    strobe_dir = base_path + "_strobe_temp"
    output_img = base_path + output_suffix + ".png"
    
    # 1. ADDED "ULTRA" and "MAX" PRESETS
    os.makedirs(strobe_dir, exist_ok=True)

    page_list = ",".join(map(str, indices))
    frame_pattern = os.path.join(strobe_dir, "strobe_%04d.png")
    
    # 2. INJECTED ANTI-ALIASING FLAGS
    gs_cmd = [
        "gs", "-dBATCH", "-dNOPAUSE", "-dQUIET", "-sDEVICE=png16m",
        f"-r{dpi}", 
        "-dTextAlphaBits=4",     # Maximum text anti-aliasing
        "-dGraphicsAlphaBits=4", # Maximum vector/line anti-aliasing
        "-dAlignToPixels=0",     # Improves sub-pixel alignment for thin plot lines
        f"-sPageList={page_list}",
        f"-sOutputFile={frame_pattern}", ps_filepath
    ]
    _run(gs_cmd, "Ghostscript extraction failed")

    # 3. Get frames
    extracted_frames = sorted(glob.glob(os.path.join(strobe_dir, "*.png")))
    
    # 4. Build filter chain with RGB enforcement
    inputs = []
    filter_chain = ""
    
    filter_chain += "[0:v]format=rgb24[v0_rgb];"
    
    for i, frame in enumerate(extracted_frames):
        inputs.extend(["-i", frame])
        if i == 0: continue
        
        filter_chain += f"[{i}:v]format=rgb24[v{i}_rgb];"
        
        prev_link = "[v0_rgb]" if i == 1 else f"[blended{i-1}]"
        next_link = f"[blended{i}]"
        
        filter_chain += f"{prev_link}[v{i}_rgb]blend=all_mode=darken{next_link};"

    current_link = f"[blended{len(extracted_frames)-1}]"

    # 5. Rotation
    if transpose:
        filter_chain += f"{current_link}transpose={transpose}[transposed];"
        current_link = "[transposed]"

    # 6. Apply the White Mask
    if mask_region:
        x1, y1, x2, y2 = mask_region
        w, h = abs(x2 - x1), abs(y2 - y1)
        fx, fy = min(x1, x2), min(y1, y2)
        filter_chain += f"{current_link}format=rgb24,drawbox=x={fx}:y={fy}:w={w}:h={h}:color=white:t=fill[masked]"
        map_link = "[masked]"
    else:
        map_link = current_link

    # 7. Final Execution
    # FFmpeg automatically uses lossless zlib compression for PNG outputs
    ffmpeg_cmd = ["ffmpeg", "-y"] + inputs + [
        "-filter_complex", filter_chain.rstrip(";"),
        "-map", map_link,
        "-pix_fmt", "rgb24", 
        output_img
    ]
    _run(ffmpeg_cmd, "FFmpeg failed")

    shutil.rmtree(strobe_dir)
    return output_img
